// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "exposures": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/rbroggi/go_aggregator/design
// --out=$(GOPATH)/src/github.com/rbroggi/go_aggregator
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// ContractHref returns the resource href.
func ContractHref(contractID interface{}) string {
	paramcontractID := strings.TrimLeftFunc(fmt.Sprintf("%v", contractID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/contract/show/%v", paramcontractID)
}

// TradeHref returns the resource href.
func TradeHref(tradeID interface{}) string {
	paramtradeID := strings.TrimLeftFunc(fmt.Sprintf("%v", tradeID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/trade/show/%v", paramtradeID)
}
