// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "exposures": Application User Types
//
// Command:
// $ goagen
// --design=github.com/rbroggi/go_aggregator/design
// --out=$(GOPATH)/src/github.com/rbroggi/go_aggregator
// --version=v1.3.1

package app
